version: "3.8"

services:
  withings-to-garmin:
    build: .
    platform: linux/amd64  # force x86_64 emulation for macOS
    image: withings-to-garmin
    container_name: withings-to-garmin
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./data:/app/data
