name: DockerHub publish

on:
  push:
    branches:
      - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set Docker Tag Based on Branch
      id: vars
      run: |
        if [ "${{ github.ref }}" == "refs/heads/master" ]; then
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
        else
          echo "DOCKER_TAG=dev" >> $GITHUB_ENV
        fi

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: artop/withings-to-garmin:${{ env.DOCKER_TAG }}
